name: CI-Stage

on:
  push:
    branches:
      - '!main'
jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.113.0'
          # extended: true

      - name: Build
        working-directory:  ./src/
        run: hugo --minify -d  ${GITHUB_WORKSPACE}/siteartifacts/stage --environment stage

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{secrets.FTP_Server}}
          username: ${{secrets.FTP_User}}
          password: ${{secrets.FTP_PWD}}
          port: 21
          state-name: deploy-state.txt
          # Folder to upload from, must end with trailing slash /
          local-dir:  ./siteartifacts/stage/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /stage/unity/
